services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"  # executa setup.sh ao iniciar
      - "/var/run/docker.sock:/var/run/docker.sock"
